Repository Sylius/SyliusMailerBundle, pull requests merged in 2022-04, with the labels that each got.

#109 Replace deprecated `setPrivate()` with `setPublic()`
  src/Bundle/DependencyInjection/SyliusMailerExtension.php
Labels: Maintenance, Bug

#113 Document array structures
  src/Component/Sender/Adapter/AdapterInterface.php
  src/Component/Sender/SenderInterface.php
Labels: Maintenance

#14 Github repository configuration from Sylius/Sylius
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/security-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Maintenance

#114 Upgrade Psalm and PHPStan
  composer.json
  phpstan.neon
  psalm.xml
  src/Component/Renderer/Adapter/AbstractAdapter.php
  src/Component/Sender/Adapter/AbstractAdapter.php
Labels: Maintenance, DX

#115 Small fixes in README
  README.md
Labels: Maintenance

#116 Branch alias should be 1.8-dev now 🖖
  composer.json
Labels: Maintenance

#118 [Sender] Assert recipient emails are always not empty strings
  src/Component/Sender/Sender.php
  src/Component/Sender/SenderInterface.php
  src/Component/spec/Sender/SenderSpec.php
Labels: Bug
